package main

import (
	"strings"
	"testing"

	"golang.org/x/crypto/ssh/knownhosts"
)

func testPublicKey(t *testing.T) string {
	t.Helper()
	_, authorizedKey := testKey(t)
	return strings.TrimSpace(string(authorizedKey))
}

// TestValidateKnownHostsCoverage locks in which files are accepted for a given
// upstream address. The expectations mirror golang.org/x/crypto/ssh/knownhosts,
// which is what sshpiper uses at connection time.
func TestValidateKnownHostsCoverage(t *testing.T) {
	key := testPublicKey(t)
	tests := []struct {
		name  string
		hosts string
		addr  string
		want  bool
	}{
		{"plain default port", "upstream.example", "upstream.example:22", true},
		{"bracketed default port", "[upstream.example]:22", "upstream.example:22", true},
		{"non default port", "[upstream.example]:2222", "upstream.example:2222", true},
		{"port mismatch", "[upstream.example]:2222", "upstream.example:22", false},
		{"missing port in pattern defaults to 22", "upstream.example", "upstream.example:2222", false},
		{"host mismatch", "other.example", "upstream.example:22", false},
		{"comma separated list", "alias.example,upstream.example", "upstream.example:22", true},
		{"wildcard host", "*.example", "upstream.example:22", true},
		{"wildcard does not cross the port", "*", "upstream.example:2222", false},
		{"question mark", "upstream?.example", "upstream1.example:22", true},
		{"negated", "*.example,!upstream.example", "upstream.example:22", false},
		{"case is significant", "UPSTREAM.example", "upstream.example:22", false},
		{"ipv6", "[2001:db8::1]:2222", "[2001:db8::1]:2222", true},
		{"ipv4", "192.0.2.10", "192.0.2.10:22", true},
		{"hashed", knownhosts.HashHostname("upstream.example"), "upstream.example:22", true},
		{"hashed non default port", knownhosts.HashHostname("[upstream.example]:2222"), "upstream.example:2222", true},
		{"hashed mismatch", knownhosts.HashHostname("other.example"), "upstream.example:22", false},
		{"revoked does not cover", "@revoked upstream.example", "upstream.example:22", false},
		{"cert authority covers", "@cert-authority *.example", "upstream.example:22", true},
		{"trailing comment", "upstream.example", "upstream.example:22", true},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			line := tc.hosts + " " + key
			if tc.name == "trailing comment" {
				line += " generated by the inventory tool"
			}
			err := ValidateKnownHosts([]byte(line+"\n"), tc.addr)
			if got := err == nil; got != tc.want {
				t.Errorf("ValidateKnownHosts(%q, %q) error = %v, want covered=%v",
					tc.hosts, tc.addr, err, tc.want)
			}
			if err != nil && tc.want == false && !strings.Contains(err.Error(), "no entry matches") {
				t.Errorf("expected a coverage error, got %v", err)
			}
		})
	}
}

func TestValidateKnownHostsRejectsMalformedFiles(t *testing.T) {
	key := testPublicKey(t)
	tests := []struct {
		name string
		in   string
		want string
	}{
		{"only a comment", "\n# nothing here\n", "no entry matches"},
		{"garbage key", "upstream.example ssh-ed25519 not-base64\n", "known_hosts:1"},
		{"missing key", "upstream.example\n", "known_hosts:1"},
		{"second line broken", "upstream.example " + key + "\nbroken\n", "known_hosts:2"},
		{"unknown marker", "@bogus upstream.example " + key + "\n", "known_hosts:1"},
		{"key type mismatch", strings.Replace("upstream.example "+key, "ssh-ed25519", "ssh-rsa", 1) + "\n", "known_hosts:1"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			err := ValidateKnownHosts([]byte(tc.in), "upstream.example:22")
			if err == nil {
				t.Fatalf("ValidateKnownHosts accepted %q", tc.in)
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("error %v does not contain %q", err, tc.want)
			}
			// The temporary file name must never leak into the message.
			if strings.Contains(err.Error(), "sshproxy-known_hosts-") {
				t.Errorf("error leaks the temporary path: %v", err)
			}
		})
	}
}
